#!/usr/bin/env bash
# Fills a development database with a season already in flight.
#
# Facts come from backend/seeds/demo.sql; the activity is generated by
# backend/cmd/seed, which drives the same use cases the running app uses — so
# scores, badges and raffle tickets follow the production rules rather than a
# second copy of them in SQL.
#
# Re-runnable: it clears the season's activity first. Never run against
# production.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root/backend"

if [[ -z "${DATABASE_URL:-}" ]]; then
  if docker compose -f "$root/docker-compose.yml" ps --status running --services 2>/dev/null | grep -qx db; then
    port="$(docker compose -f "$root/docker-compose.yml" port db 5432 2>/dev/null | cut -d: -f2)"
    export DATABASE_URL="postgresql://brag:brag@localhost:${port:-5434}/brag_dev"
    echo "→ using the compose database on port ${port:-5434}"
  else
    echo "compose is not running; set DATABASE_URL to seed directly" >&2
    exit 1
  fi
fi

go run ./cmd/seed "$@"

cat <<'ACCOUNTS'

Quick sign-in on the login screen covers these (password: demo123)
  demo.admin@brag2026.id     admin    — verification, master data, passes, raffle
  demo.captain@brag2026.id   captain  — files on behalf of Tim 1
  demo.member@brag2026.id    member   — ordinary member on Tim 2

Also seeded: ilham@wit.id / admin123, and m<team><member>@brag2026.id / member123
ACCOUNTS
